import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:proyecto_unidad1/core/models/municipioModel.dart';
import 'package:proyecto_unidad1/core/viewmodels/CRUDMunicipios.dart';

class UserProfile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final municipioProvider = Provider.of<CRUDMunicipios>(context);

    List<Municipio> lista_municipio = [
      Municipio(
          id: "023",
          nombre: "Acambay",
          significado: "Peñascos de Dios",
          cabeceraMunicipal: "Acambay",
          superficie: "492.13",
          altitud: "2,555",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "080",
          nombre: "Acolman",
          significado: "Hombre con mano o brazo",
          cabeceraMunicipal: "Acolman de Nezaualcóyotl",
          superficie: "86.88",
          altitud: "2,555",
          clima: "Seco/Templado"),
      Municipio(
          id: "032",
          nombre: "Aculco",
          significado: "En el agua torcida",
          cabeceraMunicipal: "Aculco de Espinoza",
          superficie: "465.70",
          altitud: "2,440",
          clima: "Templado"),
      Municipio(
          id: "050",
          nombre: "Almoloya de Alquisiras",
          significado: "Lugar donde mana el agua",
          cabeceraMunicipal: "Almoloya de Alquisiras",
          superficie: "167.38",
          altitud: "1,970",
          clima: "Semiarido/Templado"),
      Municipio(
          id: "102",
          nombre: "Aculco de Espinoza",
          significado: "Lugar donde mana el agua",
          cabeceraMunicipal: "Villa de Almoloya de Juarez",
          superficie: "483.77",
          altitud: "2,605",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "067",
          nombre: "Almoloya del Rio",
          significado: "Lugar donde mana el agua",
          cabeceraMunicipal: "Almoloya del Rio",
          superficie: "6.44",
          altitud: "2,610",
          clima: "Templado"),
      Municipio(
          id: "108",
          nombre: "Amanalco",
          significado: "En el estanque",
          cabeceraMunicipal: "Amanalco de Becerra",
          superficie: "219.49",
          altitud: "2,340",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "051",
          nombre: "Amatepec",
          significado: "En el cerro de los amates o árboles de papel",
          cabeceraMunicipal: "Amatepec",
          superficie: "624.94",
          altitud: "1,800",
          clima: "Calido/Semiárido/Templado"),
      Municipio(
          id: "010",
          nombre: "Amecameca",
          significado: "Lugar donde los papeles señalan",
          cabeceraMunicipal: "Aculco de Espinoza",
          superficie: "181.72",
          altitud: "2,460",
          clima: "Templado/Semifrio/Frio"),
      Municipio(
          id: "116",
          nombre: "Apaxco",
          significado: "Donde se exprime o escurre el agua",
          cabeceraMunicipal: "Apaxco de Ocampo",
          superficie: "80.34",
          altitud: "2,195",
          clima: "Seco/Templado"),
      Municipio(
          id: "081",
          nombre: "Atenco",
          significado: "Enla orilla del agua",
          cabeceraMunicipal: "San Salvador Atenco",
          superficie: "94.67",
          altitud: "2,242",
          clima: "Seco/Templado"),
      Municipio(
          id: "068",
          nombre: "Atizapan",
          significado: "En el agua o tierra blanca",
          cabeceraMunicipal: "Santa Cruz Atizapan",
          superficie: "8.42",
          altitud: "2,585",
          clima: "Templado"),
      Municipio(
          id: "100",
          nombre: "Atizapan de Zaragoza",
          significado: "En el agua o tierra blanca",
          cabeceraMunicipal: "Ciudad Adolfo Lopez Mateos",
          superficie: "89.88",
          altitud: "2,277",
          clima: "Templado"),
      Municipio(
          id: "024",
          nombre: "Atlacomulco",
          significado: "En los pozos",
          cabeceraMunicipal: "Atlacomulco de Fabela",
          superficie: "258.74",
          altitud: "2,575",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "011",
          nombre: "Atlautla",
          significado: "Donde abundan las barrancas",
          cabeceraMunicipal: "Atlautla de Victoria",
          superficie: "165.52",
          altitud: "2,575",
          clima: "Semiarido/Templado/Semifrio/Frio"),
      Municipio(
          id: "044",
          nombre: "Axapusco",
          significado: "En el aljibe de agua",
          cabeceraMunicipal: "Axapusco",
          superficie: "269.01",
          altitud: "2,345",
          clima: "Seco/Templado"),
      Municipio(
          id: "012",
          nombre: "Ayapango",
          significado: "Lugar de neblinas en las alturas",
          cabeceraMunicipal: "Ayapango de Gabriel Ramos Millán",
          superficie: "36.63",
          altitud: "2,435",
          clima: "Templado"),
      Municipio(
          id: "069",
          nombre: "Calimaya",
          significado: "Lugar en que se construyen casas",
          cabeceraMunicipal: "Calimaya de Díaz González",
          superficie: "103.11",
          altitud: "2,690",
          clima: "Templado/Semifrio/Frio"),
      Municipio(
          id: "070",
          nombre: "Capulhuac",
          significado: "En el canal de capulines",
          cabeceraMunicipal: "Capulhuac de Mirafuentes",
          superficie: "21.50",
          altitud: "2,625",
          clima: "Templado"),
      Municipio(
          id: "093",
          nombre: "Coacalco",
          significado: "En la casa de la serpiente",
          cabeceraMunicipal: "San Francisco Coacalco",
          superficie: "35.5",
          altitud: "2,268",
          clima: "Templado"),
      Municipio(
          id: "059",
          nombre: "Coatepec Harinas",
          significado: "Cerro de las serpientes",
          cabeceraMunicipal: "Coatepec Harinas",
          superficie: "35.50",
          altitud: "2,260",
          clima: "Semiarido/Templado/Semifrio"),
      Municipio(
          id: "013",
          nombre: "Cocotitlán",
          significado: "Lugar de tórtolas",
          cabeceraMunicipal: "Cocotitlán",
          superficie: "10.45",
          altitud: "2,260",
          clima: "Templado"),
      Municipio(
          id: "002",
          nombre: "Coyotepe",
          significado: "En el cerro del coyote",
          cabeceraMunicipal: "Coyotepe",
          superficie: "12.30",
          altitud: "2,305",
          clima: "Templado"),
      Municipio(
          id: "001",
          nombre: "Cuautitlán",
          significado: "Entre los árboles",
          cabeceraMunicipal: "Cuautitlán",
          superficie: "37.30",
          altitud: "2,250",
          clima: "Templado"),
      Municipio(
          id: "009",
          nombre: "Chalco",
          significado: "En el borde del lago",
          cabeceraMunicipal: "Chalco de Díaz Covarrubias",
          superficie: "234.72",
          altitud: "2,240",
          clima: "Templado"),
      Municipio(
          id: "033",
          nombre: "Chapa de Mota",
          significado: "En el río de la chía",
          cabeceraMunicipal: "Chapa de Mota",
          superficie: "289.49",
          altitud: "2,610",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "071",
          nombre: "Chapultepec",
          significado: "En el cerro del chapulín",
          cabeceraMunicipal: "Chapultepec",
          superficie: "11.82",
          altitud: "2,590",
          clima: "Templado"),
      Municipio(
          id: "082",
          nombre: "Chiautla",
          significado: "Abundancia de piedras grasosas",
          cabeceraMunicipal: "Chiautla",
          superficie: "20.13",
          altitud: "2,255",
          clima: "Seco/Templado"),
      Municipio(
          id: "083",
          nombre: "Chicoloapan",
          significado: "Lugar donde se tuerce el agua",
          cabeceraMunicipal: "Chicoloapan",
          superficie: "60.89",
          altitud: "2,245",
          clima: "Seco/Templado/Semifrio"),
      Municipio(
          id: "084",
          nombre: "Chiconcuac",
          significado: "En siete Serpientes",
          cabeceraMunicipal: "Chiconcuac de Juárez",
          superficie: "6.94",
          altitud: "2,246",
          clima: "Seco/Templado"),
      Municipio(
          id: "085",
          nombre: "Chimalhuacán",
          significado: "Lugar de escudo o rodela",
          cabeceraMunicipal: "Chimalhuacán",
          superficie: "46.61",
          altitud: "2,246",
          clima: "Seco"),
      Municipio(
          id: "109",
          nombre: "Donato Guerra",
          significado: "En honor al militar Donato Guerra",
          cabeceraMunicipal: "Villa de Donato Guerra",
          superficie: "192.19",
          altitud: "2,200",
          clima: "Semiarido/Templado/Semifrio"),
      Municipio(
          id: "094",
          nombre: "Ecatepec de Morelos",
          significado: "En el cerro del viento o del aire",
          cabeceraMunicipal: "Ecatepec de Morelos",
          superficie: "155.49",
          altitud: "2,251",
          clima: "Seco/Templado"),
      Municipio(
          id: "014",
          nombre: "Ecatzingo",
          significado: "Lugar consagrado al viento",
          cabeceraMunicipal: "Ecatzingo de Hidalgo",
          superficie: "54.71",
          altitud: "2,400",
          clima: "Semiarido/Templado/Semifrio"),
      Municipio(
          id: "003",
          nombre: "Huehuetoca",
          significado: "Lugar de la lengua antigua",
          cabeceraMunicipal: "Huehuetoca",
          superficie: "161.98",
          altitud: "2,253",
          clima: "Templado"),
      Municipio(
          id: "117",
          nombre: "Hueypoxtla",
          significado: "Lugar de grandes mercaderes",
          cabeceraMunicipal: "Hueypoxtla",
          superficie: "246.95",
          altitud: "2,253",
          clima: "Seco/Templado"),
      Municipio(
          id: "095",
          nombre: "Huixquilucan",
          significado: "Lugar lleno de cardos comestibles",
          cabeceraMunicipal: "Huixquilucan de Degollado",
          superficie: "143.52",
          altitud: "2,720",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "096",
          nombre: "Isidro Fabela",
          significado: "En honor al político y escritor Isidro Fabela",
          cabeceraMunicipal: "Tlazala de Fabela",
          superficie: "67.15",
          altitud: "2,820",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "015",
          nombre: "Ixtapaluca",
          significado: "Lugar donde se moja la sal",
          cabeceraMunicipal: "Ixtapaluca",
          superficie: "315.10",
          altitud: "2,253",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "060",
          nombre: "Ixtapan de la Sal",
          significado: "Sobre la sal",
          cabeceraMunicipal: "Ixtapan de la Sal",
          superficie: "115.37",
          altitud: "1,880",
          clima: "Semiarido/Templado"),
      Municipio(
          id: "110",
          nombre: "Ixtapan del Oro",
          significado: "Sobre la sal oro",
          cabeceraMunicipal: "Ixtapan del Oro",
          superficie: "82.49",
          altitud: "1,670",
          clima: "Semiarido/Templado"),
      Municipio(
          id: "026",
          nombre: "Ixtlahuaca",
          significado: "Llanura, tierra despoblada de árboles",
          cabeceraMunicipal: "Ixtlahuaca de Rayón",
          superficie: "336.49",
          altitud: "2,540",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "072",
          nombre: "Xalatlaco",
          significado: "En la barranca de arena",
          cabeceraMunicipal: "Xalatlaco",
          superficie: "93.23",
          altitud: "2,770",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "118",
          nombre: "Jaltenco",
          significado: "En la orilla de la arena",
          cabeceraMunicipal: "Jaltenco",
          superficie: "3.97",
          altitud: "2,235",
          clima: "Seco"),
      Municipio(
          id: "031",
          nombre: "Jilotepec",
          significado: "En el cerro de los jilotes",
          cabeceraMunicipal: "Jilotepec de Molina Enríquez",
          superficie: "586.53",
          altitud: "2,445",
          clima: "Templado"),
      Municipio(
          id: "097",
          nombre: "Jilotzingo",
          significado: "Donde se venera a Xilonen",
          cabeceraMunicipal: "Santa Ana Jilotzingo",
          superficie: "117.09",
          altitud: "2,760",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "027",
          nombre: "Jiquipilco",
          significado: "Lugar de costales o alforjas",
          cabeceraMunicipal: "Jiquipilco",
          superficie: "276.46",
          altitud: "2,750",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "028",
          nombre: "Jocotitlán",
          significado: "Entre árboles de fruta ágridulce",
          cabeceraMunicipal: "Jocotitlán",
          superficie: "49.32",
          altitud: "2,675",
          clima: "Templado/Semifrio"),
      Municipio(
          id: "073",
          nombre: "Joquicingo",
          significado: "En el barrialito",
          cabeceraMunicipal: "Joquicingo de León Guzmán",
          superficie: "49.32",
          altitud: "2,620",
          clima: "Templado"),
      Municipio(
          id: "016",
          nombre: "Juchitepec",
          significado: "Cerro de las flores",
          cabeceraMunicipal: "Juchitepec de Mariano Rivapalacio",
          superficie: "149.56",
          altitud: "2,530",
          clima: "Templado"),
      Municipio(
          id: "086",
          nombre: "La Paz",
          significado:
              "Jefes militares se reunían aquí para firmar los acuerdos de paz",
          cabeceraMunicipal: "Los Reyes Acalquipan",
          superficie: "26.71",
          altitud: "2,246",
          clima: "Seco"),
      Municipio(
          id: "038",
          nombre: "Lerma",
          significado: "Nombrado así en honor al Duque de Lerma",
          cabeceraMunicipal: "Lerma de Villada",
          superficie: "228.64",
          altitud: "2,570",
          clima: "Templado"),
      Municipio(
          id: "123",
          nombre: "Lluvianos",
          significado: "Fundador de Villa Luvianos, Cristóbal Lubiano",
          cabeceraMunicipal: "Villa Luvianos",
          superficie: "702.13",
          altitud: "1,130",
          clima: "Calido"),
      Municipio(
          id: "061",
          nombre: "Malinalco",
          significado: "la flor del malinalli",
          cabeceraMunicipal: "Malinalco",
          superficie: "186.28",
          altitud: "1,770",
          clima: "Semiarido"),
      Municipio(
          id: "004",
          nombre: "Melchor Ocampo",
          significado: "en honor al político Melchor Ocampo",
          cabeceraMunicipal: "Melchor Ocampo",
          superficie: "15.19",
          altitud: "2,260",
          clima: "Templado"),
      Municipio(
          id: "103",
          nombre: "Metepec",
          significado: "En el cerro de los magueyes",
          cabeceraMunicipal: "Metepec",
          superficie: "70.43",
          altitud: "2,619",
          clima: "Templado"),
      Municipio(
          id: "074",
          nombre: "Mexicaltzingo",
          significado: "En donde habitan los mexicanos distinguidos",
          cabeceraMunicipal: "San Mateo Mexicaltzingo",
          superficie: "12.2",
          altitud: "2,595",
          clima: "Templado"),
      Municipio(
          id: "029",
          nombre: "Morelos",
          significado: " heroe de la independencia José María Morelos",
          cabeceraMunicipal: "San Bartolo Morelos",
          superficie: "222.76",
          altitud: "2,712",
          clima: "Templado"),
      Municipio(
          id: "098",
          nombre: "Naucalpan de Juárez",
          significado: "honor al presidente Benito Juárez",
          cabeceraMunicipal: "Naucalpan de Juárez",
          superficie: "149.86",
          altitud: "2,275",
          clima: "Templado"),
      Municipio(
          id: "119",
          nombre: "Nextlalpan",
          significado: "Sobre el suelo de ceniza",
          cabeceraMunicipal: "Santa Ana Nextlalpan",
          superficie: "42.49",
          altitud: "2,235",
          clima: "Seco"),
      Municipio(
          id: "087",
          nombre: "Netzahualcoyotl",
          significado: "Coyote que ayuna",
          cabeceraMunicipal: "Ciudad Netzahualcóyotl",
          superficie: "63.44",
          altitud: "2,232",
          clima: "Templado"),
      Municipio(
          id: "099",
          nombre: "Nicolas Romero",
          significado: "honor al militar Nicolás Romero",
          cabeceraMunicipal: "Nicolas Romero",
          superficie: "233.51",
          altitud: "2,387",
          clima: "Seco"),
      Municipio(
          id: "045",
          nombre: "Nopaltepec",
          significado: "En el cerro de los nopales",
          cabeceraMunicipal: "Nopaltepec",
          superficie: "87.94",
          altitud: "2,429",
          clima: "Semifrio"),
      Municipio(
          id: "039",
          nombre: "Ocoyoacac",
          significado: "Donde principian los ocotes o pinos",
          cabeceraMunicipal: "Ocoyoacac",
          superficie: "134.71",
          altitud: "2,590",
          clima: "Templado"),
      Municipio(
          id: "062",
          nombre: "Ocuilan",
          significado: "Donde abundan los gusanos",
          cabeceraMunicipal: "Ocuilan de Arteaga",
          superficie: "344.84",
          altitud: "2,340",
          clima: "Templado"),
      Municipio(
          id: "043",
          nombre: "Otumba",
          significado: "Lugar de otomíes",
          cabeceraMunicipal: "Otumba de Gómez Farías",
          superficie: "143.42",
          altitud: "2,365",
          clima: "Cálido")
    ];
    // TODO: implement build
    //throw UnimplementedError();
    return Scaffold(
      appBar: AppBar(
        title: Center(
          child: Text('Agregar Riesgo'),
        ),
      ),
      body: RaisedButton(
        onPressed: () async {
          await municipioProvider.agregarVarios(lista_municipio);
        },
        child: Text('Agregar', style: TextStyle(color: Colors.white)),
        color: Colors.blue,
      ),
    );
  }
}
